services:

  database:
    image: "mysql:latest"
    container_name: "management-database"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Liferay
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/database/dump/*.sql:/docker-entrypoint

  liferay:
    image: "liferay/dxp:2024.q2.4"
    container_name: "management-liferay"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - JAVA_VERSION=zulu11
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_JVM_OPTS=-Xms6g -Xmx6g
    ports:
      - "8080:8080"
      - "8000:8000"
    user: root:root
    volumes:
      - ./bundles/osgi/modules/:/opt/liferay/osgi/modules
      - ./docker-compose/liferay/files/:/mnt/liferay/files/
