services:

  database:
    image: "mysql:8.0"
    container_name: "management-database"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Liferay
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/database/dump/:/docker-entrypoint-initdb.d

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: "management-elasticsearch"
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=LiferayElasticsearchCluster
      - discovery.type=single-node
      - logger.org.elasticsearch.index.query=DEBUG
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
#      - xpack.security.enabled=true
#      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.11
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  liferay:
    build:
      context: .
      dockerfile: docker-compose/liferay/Dockerfile
    image: "management-liferay"
    container_name: "management-liferay"
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    environment:
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_JVM_OPTS=-Xms6g -Xmx6g
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=5
      - JAVA_VERSION=zulu11
    ports:
      - "8080:8080"
      - "8000:8000"
      - "11311:11311"
    user: root:root
    volumes:
      - ./bundles/osgi/modules/:/opt/liferay/deploy/
      - ./docker-compose/liferay/files/:/mnt/liferay/files/

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  default:
    name: "management-network"
