services:
  database:
    image: "mysql:latest"
    container_name: "management-database"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Liferay
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/database/dump/*.sql:/docker-entrypoint

  liferay:
    image: "liferay/dxp:latest"
    container_name: "management-liferay"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "11311:11311"
      - "8080:8080"
    volumes:
      - ./docker-compose/liferay/files/:/mnt/liferay/files/
