/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.management.app.model.impl;

import com.management.app.model.Manager;
import com.management.app.service.ManagerLocalServiceUtil;

/**
 * The extended model base implementation for the Manager service. Represents a row in the &quot;Management_Manager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ManagerImpl}.
 * </p>
 *
 * @author Albert Cabral
 * @see ManagerImpl
 * @see Manager
 * @generated
 */
public abstract class ManagerBaseImpl
	extends ManagerModelImpl implements Manager {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a manager model instance should use the <code>Manager</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ManagerLocalServiceUtil.addManager(this);
		}
		else {
			ManagerLocalServiceUtil.updateManager(this);
		}
	}

}